### ISSUE TITLE
form-js 1.6 new components blog post

### ISSUE THREAD

**Issue by Skaiir** [bpmn-io/bpmn.io#185]
### What should we do?

Write out a new blog post detailing the new dynamic list and table components.

### Why should we do it?

These components enable some really nice new use cases and it's important that we educate our users about it.

----

Closed by https://github.com/bpmn-io/bpmn.io/pull/184

**Comment by nikku** [comment]
Addressed via #184 I believe?

**Comment by nikku** [comment]
I actually see https://github.com/bpmn-io/bpmn.io/pull/184 and https://github.com/bpmn-io/bpmn.io/pull/186 as interesting experiments.

I think both are somewhat ready to publish, the first one, because it is quick and concise, the second one `(v)` because of the interesting details it adds:

* `(v)` highlights some important details (showing the thoughts we put into it as we built the components): simple stacking, ...
  * I'd not not call these array, but list components though
* `(v)` gives an interesting, valuable outlook
  * We can consider to shorten that outlook, making it "likely" and move it into the wrapping up section in a "what's next paragraph". That is something we don sometimes.
  
I'd ask both of you to merge the posts at your discretion, and get back to us.
